### PR TITLE
fix(od): filter on "person" for video frame

### LINKED ISSUE #295: bug(object-detection): it detects everything, not only humans
I dig on some bugs reported by @AlexBtlle since its upgrade to v0.0.7.
I think I'm going crazy but I forgot to filter on people.
Take a look at `void ObjectDetection::interpretOutputs()` -> no filter.
So the filter should be in "mqtt-object-detection" right? But it's not!

### Specs
- bobby version:
- raspberry pi type: 4, 3 or zero.
- software: core or smart-camera

### What is wrong?
**Describe the bug**

### Actual behavior
A clear and concise description of what happens.

### PR DESCRIPTION
**Pull request by mxmaxime**
- fixes #295

Silly mistake.. I forgot to filter on detections. I think I was exhausted :sleeping: 

Thanks @AlexBtlle for reporting.

### CODE REVIEW

File: object-detection/mqtt-objectdetection.cpp [hunk 1]
```diff
@@ -506,7 +484,17 @@ class BobbyObjectDetection
...
         {
-            process_frame_video(device_id, detections, data, payload_size);
+            // The first sub_match is the whole string; the next
+            // sub_match is the first parenthesized expression.
+            if (base_match.size() == 2)
+            {
+                std::ssub_match base_sub_match = base_match[1];
+                std::string device_id = base_sub_match.str();
+
+                std::remove_if (detections.begin(), detections.end(), [](Detection const detection) { return detection.name != "person"; });
```
Comment (mxmaxime) [inline object-detection/mqtt-objectdetection.cpp:494]: That was the main missing point...

**Review by mxmaxime — COMMENTED** [review]
good to go.
